services:
  - type: web
    name: tms-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn api.index:app --host=0.0.0.0 --port=10000
    autoDeploy: true
    envVars:
      - key: TMS_AUTH_TOKEN
        sync: false
